version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "10:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: webpack
    versions:
    - 5.17.0
    - 5.19.0
    - 5.21.2
    - 5.22.0
    - 5.23.0
    - 5.24.2
    - 5.24.4
    - 5.25.1
    - 5.27.1
    - 5.28.0
    - 5.30.0
    - 5.31.2
  - dependency-name: eslint
    versions:
    - 7.22.0
    - 7.23.0
    - 7.24.0
  - dependency-name: "@babel/core"
    versions:
    - 7.12.10
    - 7.12.13
    - 7.12.16
    - 7.12.17
    - 7.13.10
    - 7.13.13
    - 7.13.14
    - 7.13.15
    - 7.13.8
  - dependency-name: css-loader
    versions:
    - 5.1.2
    - 5.1.3
    - 5.2.0
    - 5.2.1
  - dependency-name: "@babel/cli"
    versions:
    - 7.13.10
    - 7.13.14
  - dependency-name: y18n
    versions:
    - 4.0.1
  - dependency-name: "@babel/preset-env"
    versions:
    - 7.13.10
    - 7.13.12
  - dependency-name: "@blueprintjs/core"
    versions:
    - 3.38.0
    - 3.38.1
    - 3.38.2
    - 3.39.0
    - 3.40.0
    - 3.41.0
    - 3.42.0
  - dependency-name: html-webpack-plugin
    versions:
    - 4.5.1
    - 5.0.0
    - 5.1.0
    - 5.2.0
    - 5.3.0
  - dependency-name: "@babel/plugin-proposal-class-properties"
    versions:
    - 7.12.1
    - 7.12.13
    - 7.13.0
  - dependency-name: "@babel/plugin-proposal-decorators"
    versions:
    - 7.12.12
    - 7.12.13
    - 7.13.5
  - dependency-name: "@babel/preset-react"
    versions:
    - 7.12.10
    - 7.12.13
  - dependency-name: webpack-cli
    versions:
    - 4.4.0
    - 4.5.0
  - dependency-name: react
    versions:
    - 17.0.1
  - dependency-name: react-dom
    versions:
    - 17.0.1
