version: 2
jobs:
  lint:
    docker:
      - image: circleci/python:3.8-node-browsers

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          key: lint-python

      - run:
          name: Create virtualenv
          command: |
            python3 -m venv ~/venv
            echo "source ~/venv/bin/activate" >> $BASH_ENV

      - run:
          name: Install therapist
          command: pip install -U therapist

      - save_cache:
          paths:
            - "~/venv"
          key: lint-python

      - restore_cache:
          keys:
          - lint-yarn-packages-{{ checksum "yarn.lock" }}
          # fallback to using the latest cache if no exact match is found
          - lint-yarn-packages-

      - run:
          name: Install node dependencies
          command: yarn install

      - save_cache:
          paths:
            - "node_modules"
          key: lint-yarn-packages-{{ checksum "yarn.lock" }}

      # Run lint suite using therapist
      - run:
          name: Lint
          command: therapist run --use-tracked-files

  preflight:
    docker:
      - image: circleci/python:3.8-node-browsers

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: Verify the tag
          command: bin/verify-tag.py

  build-core:
    docker:
      - image: node:10.20

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
          - yarn-packages-{{ checksum "yarn.lock" }}
          # fallback to using the latest cache if no exact match is found
          - yarn-packages-

      - run:
          name: Install node dependencies
          command: yarn install

      - save_cache:
          paths:
            - "node_modules"
          key: yarn-packages-{{ checksum "yarn.lock" }}

      - run:
          name: Build package
          command: yarn workspace @identemoji/core build

      - persist_to_workspace:
          root: ~/repo
          paths:
            - packages/core/dist
            - packages/core/lib

  build-default-theme:
    docker:
      - image: node:10.20

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
          - yarn-packages-{{ checksum "yarn.lock" }}
          # fallback to using the latest cache if no exact match is found
          - yarn-packages-

      - run:
          name: Install node dependencies
          command: yarn install

      - save_cache:
          paths:
            - "node_modules"
          key: yarn-packages-{{ checksum "yarn.lock" }}

      - run:
          name: Build package
          command: yarn workspace @identemoji/default-theme build

      - persist_to_workspace:
          root: ~/repo
          paths:
            - packages/default-theme/dist
            - packages/default-theme/lib

  build-react:
    docker:
      - image: node:10.20

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
          - yarn-packages-{{ checksum "yarn.lock" }}
          # fallback to using the latest cache if no exact match is found
          - yarn-packages-

      - run:
          name: Install node dependencies
          command: yarn install

      - save_cache:
          paths:
            - "node_modules"
          key: yarn-packages-{{ checksum "yarn.lock" }}

      - run:
          name: Build package
          command: yarn workspace @identemoji/react build

      - persist_to_workspace:
          root: ~/repo
          paths:
            - packages/react/lib

  build-builder:
    docker:
      - image: node:10.20

    working_directory: ~/repo

    steps:
      - checkout

      - attach_workspace:
          at: ~/repo

      - restore_cache:
          keys:
          - yarn-packages-{{ checksum "yarn.lock" }}
          # fallback to using the latest cache if no exact match is found
          - yarn-packages-

      - run:
          name: Install node dependencies
          command: yarn install

      - save_cache:
          paths:
            - "node_modules"
          key: yarn-packages-{{ checksum "yarn.lock" }}

      - run:
          name: Build package
          command: yarn workspace @identemoji/builder build

      - persist_to_workspace:
          root: ~/repo
          paths:
            - packages/builder/dist

  deploy-ghpages:
    docker:
      - image: node:10.20

    working_directory: ~/repo

    steps:
      - checkout

      - attach_workspace:
          at: ~/repo

      - add_ssh_keys:
          fingerprints:
            - "4c:c3:e8:f5:1c:4e:07:7e:cf:8d:d8:6a:89:9e:bb:64"

      - restore_cache:
          keys:
          - yarn-packages-{{ checksum "yarn.lock" }}
          # fallback to using the latest cache if no exact match is found
          - yarn-packages-

      - run:
          name: Install dependencies
          command: yarn install --frozen-lockfile

      - save_cache:
          paths:
            - "node_modules"
          key: yarn-packages-{{ checksum "yarn.lock" }}

      - run:
          name: Build Theme Builder
          command: yarn workspace @identemoji/builder build

      - run:
          name: Install gh-pages and configure
          command: |
            yarn global add gh-pages
            git config user.email "ci-build@re.hn"
            git config user.name "ci-build"

      - run:
          name: Deploy content to gh-pages branch
          command: gh-pages --dist packages/builder/dist -m "Updates [ci skip]"

  publish:
    docker:
      - image: node:10.20

    working_directory: ~/repo

    steps:
      - checkout

      - attach_workspace:
          at: ~/repo

      - run:
          name: Configure Yarn
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/repo/.npmrc

      - run:
          name: Publish @identemoji/core
          command: |
            yarn workspace @identemoji/core publish --non-interactive --new-version ${CIRCLE_TAG#"v"} --access=public

      - run:
          name: Publish @identemoji/default-theme
          command: |
            yarn workspace @identemoji/default-theme publish --non-interactive --new-version ${CIRCLE_TAG#"v"} --access=public

      - run:
          name: Publish @identemoji/react
          command: |
            yarn workspace @identemoji/react publish --non-interactive --new-version ${CIRCLE_TAG#"v"} --access=public

workflows:
  version: 2
  test-build-deploy:
    jobs:
      # Test
      - lint:
          filters:
            tags:
              only: /.*/

      # Build
      - build-core:
          filters:
            tags:
              only: /.*/
      - build-default-theme:
          filters:
            tags:
              only: /.*/
      - build-react:
          filters:
            tags:
              only: /.*/
      - build-builder:
          requires:
            - build-core
            - build-default-theme
            - build-react
          filters:
            tags:
              only: /.*/

      # Deploy
      - preflight:
          requires:
            - lint
            - build-core
            - build-default-theme
            - build-react
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
      - publish:
          requires:
            - preflight
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
      - deploy-ghpages:
          requires:
            - build-builder
          filters:
            branches:
              only: master
